title: YOUR TITLE
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://gtxaspec.github.io/thingino-wiki/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://gtxaspec.github.io/thingino-wiki/
