name: Mirror Wiki to GitHub Pages

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pages repository
        uses: actions/checkout@v4
        with:
          repository: gtxaspec/thingino-wiki  # Your GitHub Pages repository
          token: ${{ secrets.GITHUB_TOKEN }}
          path: pages-repo

      - name: Clone Wiki repository
        run: git clone https://github.com/themactep/thingino-firmware.wiki.git wiki-repo

      - name: Sync Wiki to Pages
        run: |
          rsync -av --delete wiki-repo/ pages-repo/
          cd pages-repo
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update GitHub Pages from wiki" || echo "No changes to commit"
          git stash  # Stash any uncommitted changes
          git pull --rebase origin master  # Pull the latest changes
          git stash pop || echo "No stash entries to pop"  # Reapply the stashed changes if any
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gtxaspec/thingino-wiki.git master
